image: ubuntu:latest
variables:
  APP_NAME: web
  WORK_DIR: ${CI_PROJECT_NAME}
  # BRANCH: ${CI_COMMIT_REF_NAME}
  REPO: https://gitlab.com/pebblo/frontend.git
stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - apt-get update -qq
    - apt-get install -qq git
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh -o StrictHostKeyChecking=no root@"$PRD_SERVER" "rm -rf ~/${WORK_DIR]; mkdir ~/${WORK_DIR}; git clone ${REPO}; cd ${WORK_DIR}; npm install -g yarn; yarn; yarn build; yarn start"
  only:
  - develop
