image: ubuntu:latest
variables:
  APP_NAME: web
  WORK_DIR: ${CI_PROJECT_NAME}
  # BRANCH: ${CI_COMMIT_REF_NAME}
  REPO: https://gitlab.com/pebblo/frontend.git
stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    # - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - apt-get update -qq
    - apt-get install -qq git
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh-add <(echo "$PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no ubuntu@"$PRD_SERVER" "rm -rf ~/${WORK_DIR]; git clone ${REPO}; cd ${WORK_DIR}; npm install yarn -g; yarn; yarn build; yarn start"

  only:
  - develop