// Generated by dts-bundle v0.7.3

declare module 'pulse-framework/next' {
    export function preserveServerState(nextProps: {
        [key: string]: any;
    }, core: {
        [key: string]: any;
    }): {
        [key: string]: any;
    };
    export function loadServerState(core: {
        [key: string]: any;
    }): void;
    export function isServer(): boolean;
}

